swagger: "2.0"
info:
  title: api_yext/v1/api.proto
  version: version not set
tags:
  - name: ApiService
consumes:
  - application/json
produces:
  - application/json
paths:
  /apiyext.v1.ApiService/SearchListings:
    post:
      operationId: ApiService_SearchListings
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SearchResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SearchRequest'
      tags:
        - ApiService
definitions:
  apiyextv1Status:
    type: string
    enum:
      - IN_PROGRESS
      - FINISHED
    default: IN_PROGRESS
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  v1Location:
    type: object
    properties:
      id:
        type: string
        title: The id that represents the location within the underlying service
      companyName:
        type: string
        title: The name of the location
      address:
        type: string
        title: The postal address of the location
      locality:
        type: string
        title: This typically refers to a city, but may refer to a suburb or a neighborhood in certain countries
      state:
        type: string
        title: The state or territory abbreviation
      country:
        type: string
        title: The country code
      zipCode:
        type: string
        title: A string specifying the zip code or postal code
      website:
        type: string
        title: The website of the location
      phone:
        type: string
        title: The primary phone number of the location
      url:
        type: string
        title: The url location of where you can find the location on the internet
      externalId:
        type: string
        title: The external id for the location on that site
      reviewCount:
        type: string
        format: int64
        title: The number of reviews that the location has
      reviewRating:
        type: number
        format: float
        title: The average rating for the reviews
      sourceId:
        type: string
        format: int64
        title: Source ID for the location
      matchName:
        type: boolean
        title: If the name is scored high enough to be considered a match
      matchAddress:
        type: boolean
        title: If the address is scored high enough to be considered a match
      matchPhone:
        type: boolean
        title: If the phone is scored high enough to be considered a match
    title: Location is a holder for search results from the corresponding api that a search is for
  v1SearchRequest:
    type: object
    properties:
      companyName:
        type: string
        title: The name of the location
      address:
        type: string
        title: Address of the location
      locality:
        type: string
        title: Usually city, could also be a neighbourhood
      state:
        type: string
        title: State of location
      country:
        type: string
        title: Country of location
      zipCode:
        type: string
        title: Zip code or postal of location
      phone:
        type: string
        title: Phone Number of location
      sourceIds:
        type: array
        items:
          type: string
          format: int64
        title: Source IDs to search for
    title: A request to perform search for business
  v1SearchResponse:
    type: object
    properties:
      locations:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Location'
        title: list of locations that were found
      status:
        $ref: '#/definitions/apiyextv1Status'
        title: If we need to call back later to get the results
    title: Search response returns the location data
