swagger: "2.0"
info:
  title: wsp_monitor/v1/api.proto
  version: version not set
tags:
  - name: Monitor
consumes:
  - application/json
produces:
  - application/json
paths:
  /wsp_monitor.v1.Monitor/BackFillAccountGroupName:
    post:
      operationId: Monitor_BackFillAccountGroupName
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties: {}
      tags:
        - Monitor
  /wsp_monitor.v1.Monitor/BackFillActivationStatus:
    post:
      operationId: Monitor_BackFillActivationStatus
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties: {}
      tags:
        - Monitor
  /wsp_monitor.v1.Monitor/GetDiscrepancyData:
    post:
      operationId: Monitor_GetDiscrepancyData
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetDiscrepancyDataResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties: {}
      tags:
        - Monitor
  /wsp_monitor.v1.Monitor/GetSiteId:
    post:
      operationId: Monitor_GetSiteId
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetSiteIdResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetSiteIdRequest'
      tags:
        - Monitor
  /wsp_monitor.v1.Monitor/ListHealthCheckPID:
    post:
      operationId: Monitor_ListHealthCheckPID
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SearchResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SearchRequest'
      tags:
        - Monitor
  /wsp_monitor.v1.Monitor/ListHealthChecks:
    post:
      operationId: Monitor_ListHealthChecks
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListHealthChecksResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListHealthChecksRequest'
      tags:
        - Monitor
  /wsp_monitor.v1.Monitor/ListHealthChecksVstore:
    post:
      operationId: Monitor_ListHealthChecksVstore
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListHealthChecksVstoreResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1ListHealthChecksVstoreRequest'
      tags:
        - Monitor
  /wsp_monitor.v1.Monitor/Search:
    post:
      summary: Search elasticsearch for WordPress sites according to search queries and filters
      operationId: Monitor_Search
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UptimeSearchResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1UptimeSearchRequest'
      tags:
        - Monitor
  /wsp_monitor.v1.Monitor/UpdatePid:
    post:
      operationId: Monitor_UpdatePid
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties: {}
      tags:
        - Monitor
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1GetDiscrepancyDataResponse:
    type: object
    properties:
      discrepancyData:
        type: array
        items:
          type: string
  v1GetSiteIdRequest:
    type: object
    properties:
      accountId:
        type: string
  v1GetSiteIdResponse:
    type: object
    properties:
      siteId:
        type: string
  v1HealthCheck:
    type: object
    properties:
      state:
        type: string
      error:
        type: string
      status:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1HealthCheckStatus'
      createdAt:
        type: string
        format: date-time
  v1HealthCheckStatus:
    type: object
    properties:
      type:
        type: string
      value:
        type: integer
        format: int32
  v1HealthCheckValues:
    type: object
    properties:
      state:
        type: string
      created:
        type: string
        format: date-time
      updated:
        type: string
        format: date-time
  v1ListHealthChecksRequest:
    type: object
    properties:
      siteId:
        type: string
      cursor:
        type: integer
        format: int32
      pageSize:
        type: integer
        format: int32
  v1ListHealthChecksResponse:
    type: object
    properties:
      results:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1HealthCheck'
      nextCursor:
        type: integer
        format: int32
  v1ListHealthChecksVstoreRequest:
    type: object
    properties:
      siteId:
        type: string
      cursor:
        type: string
      pageSize:
        type: integer
        format: int32
  v1ListHealthChecksVstoreResponse:
    type: object
    properties:
      list:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1HealthCheckValues'
      nextCursor:
        type: string
  v1SearchRequest:
    type: object
    properties:
      partnerId:
        type: string
  v1SearchResponse:
    type: object
    properties:
      sites:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1SiteHealth'
      totalResults:
        type: string
        format: int64
  v1SiteHealth:
    type: object
    properties:
      siteId:
        type: string
      currentHealth:
        type: string
      siteActivationStatus:
        type: boolean
  v1SiteHealths:
    type: object
    properties:
      partnerId:
        type: string
      siteId:
        type: string
      accountGroupName:
        type: string
      uptime1day:
        type: string
      uptime7days:
        type: string
      uptime30days:
        type: string
      currentHealth:
        type: string
      statusCode:
        type: string
      activationStatus:
        type: string
      accountId:
        type: string
  v1UptimeSearchRequest:
    type: object
    properties:
      partnerId:
        type: string
  v1UptimeSearchResponse:
    type: object
    properties:
      siteHealths:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1SiteHealths'
        title: The cursor to use for the next healthcheckData
      totalResults:
        type: string
        format: int64
        title: The total number of results for this query across all pages
