swagger: "2.0"
info:
  title: contract_billing/v1/api.proto
  version: version not set
tags:
  - name: ContractBilling
consumes:
  - application/json
produces:
  - application/json
paths:
  /contract_billing.v1.ContractBilling/CreateCustomer:
    post:
      operationId: ContractBilling_CreateCustomer
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateCustomerResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateCustomerRequest'
      tags:
        - ContractBilling
  /contract_billing.v1.ContractBilling/GetBankNames:
    post:
      operationId: ContractBilling_GetBankNames
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetBankNamesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetBankNamesRequest'
      tags:
        - ContractBilling
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1Bank:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      ibtCode:
        type: string
      accountType:
        type: string
      accountHolderName:
        type: string
      accountNumber:
        type: string
      mandateAuthorisedName:
        type: string
      mandateReceived:
        type: string
        format: date-time
      mandateDayFirst:
        type: string
        format: int64
      mandateDayRest:
        type: string
        format: int64
      default:
        type: boolean
  v1BillToAddress:
    type: object
    properties:
      id:
        type: string
      addressLine1:
        type: string
      addressLine2:
        type: string
      addressLine3:
        type: string
      addressLine4:
        type: string
      postalCode:
        type: string
      city:
        type: string
      province:
        type: string
      default:
        type: boolean
  v1ContactPerson:
    type: object
    properties:
      id:
        type: string
      firstName:
        type: string
      surname:
        type: string
      title:
        type: string
      contactPosition:
        type: string
      phoneNumber:
        type: string
      faxNumber:
        type: string
      mobileNumber:
        type: string
      emailAddress:
        type: string
      contractSigner:
        type: boolean
      default:
        type: boolean
  v1CreateCustomerRequest:
    type: object
    properties:
      customer:
        $ref: '#/definitions/v1Customer'
  v1CreateCustomerResponse:
    type: object
    properties:
      internalCustomerId:
        type: string
  v1Customer:
    type: object
    properties:
      internalCustomerId:
        type: string
        title: Internally stored fields
      name:
        type: string
      website:
        type: string
      externalCustomerId:
        type: string
      businessIds:
        type: array
        items:
          type: string
      creditBureauNumber:
        type: string
        title: Fields fetched externally. Sensitive fields will be truncated and will not return all of the data
      creditBureauRating:
        type: string
      creditBureauDate:
        type: array
        items:
          type: string
          format: date-time
      companyRegistrationNumber:
        type: string
      creditVettingCode:
        type: string
      vatRegistrationNumber:
        type: string
      emailAddress:
        type: string
      banks:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Bank'
      billToAddresses:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1BillToAddress'
      contactPersons:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1ContactPerson'
  v1GetBankNamesRequest:
    type: object
    title: Placeholder for future args
  v1GetBankNamesResponse:
    type: object
    properties:
      names:
        type: array
        items:
          type: string
