swagger: "2.0"
info:
  title: vendasta_login_center/v1/api.proto
  version: version not set
tags:
  - name: Login
consumes:
  - application/json
produces:
  - application/json
paths:
  /login.v1.Login/GetCode:
    post:
      summary: Get a code that can be exchanged for a session
      operationId: Login_GetCode
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetCodeResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetCodeRequest'
      tags:
        - Login
  /login.v1.Login/SendResetPasswordEmail:
    post:
      summary: Request a Password Reset email for a user
      operationId: Login_SendResetPasswordEmail
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SendResetPasswordEmailRequest'
      tags:
        - Login
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1GetCodeRequest:
    type: object
    properties:
      namespace:
        type: string
        title: the namespace of the subject being logged into
      login:
        $ref: '#/definitions/v1LoginCredentials'
      token:
        $ref: '#/definitions/v1TokenCredentials'
      googleCredentials:
        $ref: '#/definitions/v1GoogleCredentials'
      linkedinCredentials:
        $ref: '#/definitions/v1LinkedInCredentials'
      microsoftCredentials:
        $ref: '#/definitions/v1MicrosoftCredentials'
      type:
        type: string
        title: the type of the subject being logged into
    title: a request to get a code
  v1GetCodeResponse:
    type: object
    properties:
      code:
        type: string
        title: A code that can be exchanged for a session
    title: a response containg a code
  v1GoogleCredentials:
    type: object
    properties:
      idToken:
        type: string
        title: The identity token
    title: login with a google identity token
  v1LinkedInCredentials:
    type: object
    properties:
      accessToken:
        type: string
        title: The LinkedIn access token
    title: login with a linkedin access token
  v1LoginCredentials:
    type: object
    properties:
      email:
        type: string
        title: a user's email
      password:
        type: string
        title: a user's password
    title: login with username and password credentials
  v1MicrosoftCredentials:
    type: object
    properties:
      idToken:
        type: string
  v1SendResetPasswordEmailRequest:
    type: object
    properties:
      userId:
        type: string
        description: The IAM User ID of the user to send a reset password email to.
      serviceProviderId:
        type: string
        description: The service provider to send the user to after completing a password reset.
      serviceContext:
        type: string
        title: |-
          The base64 encoded service context which sso will use to send the user
          back into your app after resetting their password
      usePlatformDefaultDomain:
        type: boolean
        title: Controls whether the welcome email is sent from a preconfigured domain that is guaranteed to be authorized
    title: Request a Password Reset email for a user
  v1TokenCredentials:
    type: object
    properties:
      idToken:
        type: string
        title: The identity token
      provider:
        type: string
        description: Who is the provider of the token, e.g. Google, Facebook, etc.
    title: login with an identity token
